name: golangci-lint
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  golangci119:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20.x"]
        os: [ubuntu-latest, windows-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }} 
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2
        args: --timeout=25m
        only-new-issues: true
